### PR TITLE
Adding Defenses VS Boss

### PR DESCRIPTION
**Pull request by TheJakeMF**
I added a Defenses VS Boss tab (like your Melee VS Boss) and adjusted dodge/parry/block methods to accommodate level differential by adding a second parameter (leveldiff).

### CODE REVIEW

**Comment by pepopo978** [comment]
cool seems like you undid a lot of otari changes though which will make it hard to merge his stuff in the future - I'll try to isolate what you changed

**Comment by TheJakeMF** [comment]
I forked your version instead of his; my changes are pretty simple to replicate, but I will make a modification to his fork as well to make it simpler.

**Comment by pepopo978** [comment]
> I forked your master instead of that one; my changes are pretty simple to replicate, but I will make a modification to his fork as well to make it simpler.

don't bother he won't accept it - he doesn't think extra tabs like this are worth adding.  Could you change this PR to just have your new tab stuff?

**Comment by TheJakeMF** [comment]
Just saw your last reply, will undo my last commit.

**Comment by TheJakeMF** [comment]
I isolated the LUA functions I modified and put them here if you want to simply copy/paste them into your version since I did not give ya a nice pull request. 

[BCS_Modifications.txt](https://github.com/user-attachments/files/18278000/BCS_Modifications.txt)

**Pull request closed without merging**
